name: CCR Test Workflow
# This workflow is triggered on pull requests to main branch
on:
  workflow_dispatch:
    inputs:
      ref:
        default: main
        description: Branch or tag to build
        required: true
        type: string
      jdks:
        default: '21,25'
        description: JDK versions to build for
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        default: main
        description: Branch or tag to build
        required: true
        type: string
      jdks:
        default: '21,25'
        description: JDK versions to build for
        required: true
        type: string
# We build for all combinations but run tests only on one combination (linux & latest java)
jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch
  set-jdk:
    name: Set target JDKs list
    runs-on: ubuntu-latest
    outputs:
      jdks: ${{ steps.jdks-list.outputs.jdks_json }}
    steps:
      - name: Set JDKs list
        id: jdks-list
        run: |
          input="${{ inputs.jdks }}"
          cleaned=$(echo "$input" | tr -d '[:space:]')
          array=$(jq -Rc 'split(",") | map(select(. != ""))' <<< "$cleaned")
          echo "jdks_json=$array" >> $GITHUB_OUTPUT
  build-test-linux:
    strategy:
      matrix:
        java: ${{ fromJSON(needs.set-jdk.outputs.jdks) }}
    name: Build CCR Plugin on Linux using Container Image
    runs-on: ubuntu-latest
    needs: [Get-CI-Image-Tag,set-jdk]
    container:
      # using the same image which is used by opensearch-build team to build the OpenSearch Distribution
      # this image tag is subject to change as more dependencies and updates will arrive over time
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      # need to switch to root so that github actions can install runner binary on container without permission issues.
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}

    steps:
      - name: Run start commands
        run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}
      - name: Checkout CCR
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Run build
        # switching the user, as OpenSearch cluster can only be started as root/Administrator on linux-deb/linux-rpm/windows-zip.
        run: |
          chown -R 1000:1000 `pwd`
          su `id -un 1000` -c 'whoami && java -version && ./gradlew --refresh-dependencies clean release -D"build.snapshot=true"'
      - name: Upload failed logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: |
            build/testclusters/integTest-*/logs/*
            build/testclusters/leaderCluster-*/logs/*
            build/testclusters/followCluster-*/logs/*
      - name: Create Artifact Path
        run: |
          mkdir -p cross-cluster-replication-artifacts
          cp ./build/distributions/*.zip cross-cluster-replication-artifacts
          cd cross-cluster-replication-artifacts
          for file in *.zip; do
            [[ -f "$file" ]] || continue
            name="${file%.zip}"
            new_name="${name}-${{ matrix.java }}.zip"
            if [[ "$name" != "$new_name" ]]; then
              mv -i -- "$file" "$new_name"
            fi
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          path: cross-cluster-replication-artifacts/*
          name: cross-cluster-replication-artifact-${{ matrix.java }}
